package main

import "net/http"

func serveUI(w http.ResponseWriter, r *http.Request) {
	if r.URL.Path != "/" {
		http.NotFound(w, r)
		return
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	_, _ = w.Write([]byte(indexHTML))
}

const indexHTML = `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>BiliGreen</title><style>
:root{color-scheme:dark;--bg:#0c1017;--card:#171d28;--line:#2a3445;--text:#edf2ff;--muted:#96a3ba;--brand:#fb7299}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 15% 0,#242e47 0,transparent 31%),var(--bg);font:15px/1.5 system-ui,sans-serif;color:var(--text)}header{position:sticky;top:0;z-index:2;background:#0c1017e8;backdrop-filter:blur(14px);border-bottom:1px solid var(--line)}nav,main{max-width:1080px;margin:auto;padding:14px 20px}nav{display:flex;align-items:center;gap:8px}.logo{font-size:24px;font-weight:850;margin-right:auto}.logo b{color:var(--brand)}button,.tab{border:0;border-radius:9px;background:#252d3c;color:var(--text);font-weight:650;padding:10px 14px;cursor:pointer}.primary{background:var(--brand);color:#fff}.tab.active{background:#384257}.status{color:var(--muted);font-size:13px}main{padding-top:24px}.toolbar{display:flex;gap:10px;margin-bottom:18px}input,select{border:1px solid var(--line);background:#101621;color:var(--text);padding:11px 13px;border-radius:9px;outline:0}input{flex:1}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:15px}.card{background:var(--card);border:1px solid var(--line);border-radius:14px;overflow:hidden}.card img{width:100%;aspect-ratio:16/10;object-fit:cover;background:#0d121b}.body{padding:13px}.title{font-weight:700;min-height:45px}.meta,.hint{color:var(--muted);font-size:13px}.card button{width:100%;margin-top:10px}.panel{background:var(--card);border:1px solid var(--line);padding:16px;border-radius:14px;margin-bottom:18px}.download-location{border-color:#586987;background:linear-gradient(135deg,#1b2638,#171d28)}.path-display{font-size:14px;color:#fff;overflow-wrap:anywhere;margin:8px 0}.row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.row>*{flex:1}.hidden{display:none!important}.task{padding:12px 0;border-top:1px solid var(--line)}progress{width:100%;accent-color:var(--brand)}dialog{background:var(--card);color:var(--text);border:1px solid var(--line);border-radius:14px;padding:22px;max-width:720px;width:92%}dialog::backdrop{background:#000a}dialog input{width:100%;margin:10px 0}video{width:100%;max-height:72vh;background:#000;border-radius:10px}.error{color:#ff8f9d}.success{color:#68d9a1}@media(max-width:720px){nav{flex-wrap:wrap}.logo{width:100%}.toolbar{flex-wrap:wrap}.toolbar input{min-width:100%}}
</style></head><body><header><nav><div class="logo">Bili<b>Green</b></div><button class="tab active" data-view="feed">热门</button><button class="tab" data-view="search">搜索</button><button class="tab" data-view="favorites">收藏夹</button><button id="login">登录</button><button id="shutdown">退出程序</button><span id="account" class="status">未登录</span></nav></header><main>
<section class="panel download-location"><strong>下载保存位置</strong><div id="pathDisplay" class="path-display">正在读取…</div><div class="row"><input id="output" placeholder="输入自定义下载目录"><button id="savePath">应用目录</button><button id="openFolder" class="primary">打开下载目录</button></div><div class="hint">默认使用系统“下载/BiliGreen”文件夹；自定义路径仅保存在此浏览器中。</div></section>
<section id="feedView"><div class="toolbar"><strong>即时热门</strong><button id="refresh">刷新推送</button></div><div id="feed" class="grid"></div></section>
<section id="searchView" class="hidden"><div class="toolbar"><input id="keyword" placeholder="搜索 B 站视频"><button id="searchBtn" class="primary">搜索</button></div><div id="results" class="grid"></div></section>
<section id="favoritesView" class="hidden"><div class="panel"><div class="row"><select id="folder"></select><label>加载/下载数量（0=全部）<input id="batchLimit" type="number" min="0" value="20"></label><button id="loadFolder">加载列表</button></div><div class="row"><label>批量类型 <select id="batchMode"><option value="video">视频</option><option value="audio">仅音频（最高音质）</option></select></label><label>视频清晰度 <select id="batchQN"><option value="127">每个视频的最高可用</option><option value="120">4K</option><option value="116">1080P 60帧</option><option value="112">1080P+</option><option value="80">1080P</option><option value="64">720P</option></select></label><label>下载后处理 <select id="after"><option value="">保留在原收藏夹</option><option value="remove">取消收藏</option><option value="move">迁移到另一收藏夹</option></select></label><label id="targetWrap" class="hidden">目标收藏夹 <select id="target"></select></label></div><div class="row"><button id="selectAll">全选/取消全选</button><button id="batchDownload" class="primary">下载已勾选视频</button></div><div class="hint">数量设为 0 可加载并一键下载整个收藏夹；多 P 视频会下载全部分 P。仅在文件完整下载成功后执行收藏夹后处理。</div></div><div id="favoriteItems" class="grid"></div></section>
<section class="panel" style="margin-top:22px"><strong>下载任务</strong><div id="tasks" class="hint">暂无任务</div></section></main>
<dialog id="loginDialog"><h3>扫码登录</h3><div style="text-align:center"><img id="qr" alt="登录二维码" style="width:256px;height:256px;background:white;border-radius:10px"><p id="qrStatus" class="hint">正在生成二维码…</p><button id="newQR">刷新二维码</button></div><details><summary>Cookie 备用登录</summary><p class="hint">不支持输入账号密码：避免本工具接触你的明文密码。Cookie 仅存于程序内存。</p><input id="cookie" type="password" placeholder="SESSDATA=...; bili_jct=..."><button id="loginSubmit" type="button" class="primary">验证 Cookie</button></details><div id="loginMsg" class="error"></div><button id="closeLogin">关闭</button></dialog>
<dialog id="downloadDialog"><h3 id="downloadTitle">下载</h3><div id="videoMeta" class="hint"></div><div class="row"><label>下载类型<select id="mode"><option value="video">视频（含音频）</option><option value="audio">仅音频</option></select></label><label>分 P<select id="page"></select></label><label id="qualityWrap">质量<select id="qn"></select></label></div><div id="qualityHint" class="hint">正在检测实际可用质量…</div><div class="hint">保存到：<span id="dialogPath"></span></div><div class="row"><button id="cancelDownload">取消</button><button id="confirmDownload" class="primary">开始下载</button></div></dialog>
<dialog id="playerDialog"><h3 id="playerTitle">本地播放</h3><div id="playerMeta" class="hint"></div><video id="player" controls playsinline></video><div id="playerError" class="error"></div><button id="closePlayer">关闭播放器</button></dialog>
<script>
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),plain=s=>String(s??'').replace(/<[^>]*>/g,'');let folders=[],chosen=null,qrTimer=null,freshIndex=0,currentFavoriteItems=[];
async function req(path,opt){let r=await fetch(path,opt),j=await r.json();if(!r.ok)throw Error(j.error||'请求失败');return j}async function post(path,data){return req(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)})}
function formatTime(v){if(typeof v==='string')return v;v=+v||0;let h=Math.floor(v/3600),m=Math.floor(v%3600/60),s=Math.floor(v%60);return(h?h+':':'')+String(m).padStart(h?2:1,'0')+':'+String(s).padStart(2,'0')}function cards(el,items,sourceFolder=0){$(el).innerHTML=items.length?items.map(v=>'<article class="card">'+(sourceFolder?'<label class="body"><input class="favCheck" type="checkbox" data-bvid="'+esc(v.bvid)+'" checked> 选择</label>':'')+'<img loading="lazy" src="/api/image?url='+encodeURIComponent(v.pic||'')+'"><div class="body"><div class="title">'+esc(plain(v.title))+'</div><div class="meta">'+esc(v.author||v.owner?.name||'')+(v.duration?' · '+formatTime(v.duration):'')+'</div><button class="primary download" data-bvid="'+esc(v.bvid)+'" data-aid="'+(v.aid||0)+'" data-folder="'+sourceFolder+'">单独下载</button></div></article>').join(''):'<p class="hint">没有内容</p>'}
async function feed(){let b=$('#refresh');b.disabled=true;b.textContent='刷新中…';try{freshIndex++;let items=await req('/api/feed?fresh='+freshIndex+'&_='+Date.now());cards('#feed',items);b.textContent='已换一批';setTimeout(()=>b.textContent='刷新推送',900)}catch(e){$('#feed').innerHTML='<p class="error">'+esc(e.message)+'</p>';b.textContent='重试'}finally{b.disabled=false}}
async function search(){let q=$('#keyword').value.trim();if(!q)return;$('#results').innerHTML='<p class="hint">搜索中…</p>';try{cards('#results',await req('/api/search?q='+encodeURIComponent(q)))}catch(e){$('#results').innerHTML='<p class="error">'+esc(e.message)+'</p>'}}
async function sessionStatus(){try{let u=await req('/api/session');$('#account').textContent=u.isLogin?u.uname:'未登录';$('#login').textContent=u.isLogin?'切换账号':'登录';if(u.isLogin)await loadFolders()}catch(e){$('#account').textContent='登录检查失败'}}
async function loadFolders(){try{folders=await req('/api/favorites');let html=folders.map(f=>'<option value="'+f.id+'">'+esc(f.title)+'（'+f.media_count+'）</option>').join('');$('#folder').innerHTML=html;$('#target').innerHTML=html}catch(e){$('#favoriteItems').innerHTML='<p class="error">'+esc(e.message)+'</p>'}}
async function loadFavorite(){let id=+$('#folder').value,limit=Math.max(0,+$('#batchLimit').value||0);if(!id)return;$('#favoriteItems').innerHTML='<p class="hint">正在加载…</p>';try{currentFavoriteItems=await req('/api/favorite/items?folder='+id+'&limit='+limit);cards('#favoriteItems',currentFavoriteItems,id)}catch(e){$('#favoriteItems').innerHTML='<p class="error">'+esc(e.message)+'</p>'}}
async function loadQualities(){let p=chosen.info.pages[+$('#page').value],audio=$('#mode').value==='audio',endpoint=audio?'/api/audio-qualities':'/api/qualities';$('#qn').disabled=true;$('#qualityHint').textContent='正在检测实际可用'+(audio?'音质':'清晰度')+'…';let qs=await post(endpoint,{bvid:chosen.info.bvid,cid:p.cid});$('#qn').innerHTML=qs.map((q,n)=>'<option value="'+q.id+'">'+(n===0&&audio?'最高音质 · ':'')+esc(q.label)+(q.width?' · '+q.width+'×'+q.height:'')+(q.codec?' · '+esc(q.codec):'')+'</option>').join('');$('#qn').disabled=false;$('#qualityHint').textContent=qs.length?'列表来自当前视频和账号的实时媒体流':'没有检测到可下载质量'}
document.addEventListener('click',async e=>{let b=e.target.closest('.download');if(!b)return;try{let i=await post('/api/info',{url:b.dataset.bvid});chosen={info:i,aid:+b.dataset.aid,sourceFolder:+b.dataset.folder};$('#downloadTitle').textContent=i.title;$('#videoMeta').textContent='总长度 '+formatTime(i.duration)+' · 共 '+i.pages.length+' P';$('#page').innerHTML=i.pages.map((p,n)=>'<option value="'+n+'">P'+p.page+' · '+esc(p.part)+' · '+formatTime(p.duration)+'</option>').join('');$('#mode').value='video';$('#dialogPath').textContent=$('#output').value;$('#downloadDialog').showModal();await loadQualities()}catch(x){alert(x.message)}});
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));['feed','search','favorites'].forEach(v=>$('#'+v+'View').classList.toggle('hidden',v!==b.dataset.view));if(b.dataset.view==='favorites')loadFolders()});
$('#refresh').onclick=feed;$('#searchBtn').onclick=search;$('#keyword').onkeydown=e=>{if(e.key==='Enter')search()};$('#loadFolder').onclick=loadFavorite;$('#page').onchange=loadQualities;$('#mode').onchange=loadQualities;$('#after').onchange=()=>$('#targetWrap').classList.toggle('hidden',$('#after').value!=='move');$('#batchMode').onchange=()=>$('#batchQN').disabled=$('#batchMode').value==='audio';$('#selectAll').onclick=()=>{let cs=[...document.querySelectorAll('.favCheck')],on=cs.some(x=>!x.checked);cs.forEach(x=>x.checked=on)};
$('#batchDownload').onclick=async()=>{let selected=new Set([...document.querySelectorAll('.favCheck:checked')].map(x=>x.dataset.bvid)),items=currentFavoriteItems.filter(x=>selected.has(x.bvid));if(!items.length)return alert('请先勾选视频');if(!confirm('将把 '+items.length+' 个收藏视频加入下载队列，继续吗？'))return;let folder=+$('#folder').value,after=$('#after').value,target=+$('#target').value,mode=$('#batchMode').value,qn=mode==='audio'?0:+$('#batchQN').value,output=$('#output').value;$('#batchDownload').disabled=true;for(let [index,v] of items.entries()){try{let info=await post('/api/info',{url:v.bvid});for(let [partIndex,p] of info.pages.entries())await post('/api/download',{bvid:info.bvid,cid:p.cid,aid:v.aid,title:info.title,part:p.part,mode,qn,output,duration:p.duration,pageNumber:p.page,pageCount:info.pages.length,after:partIndex===info.pages.length-1?after:'',sourceFolder:folder,targetFolder:target})}catch(e){console.error(v.bvid,e)}$('#batchDownload').textContent='加入队列 '+(index+1)+'/'+items.length}$('#batchDownload').disabled=false;$('#batchDownload').textContent='下载已勾选视频';refreshTasks()};
async function startQR(){clearInterval(qrTimer);$('#qrStatus').textContent='正在生成二维码…';try{let q=await post('/api/qr/start',{});$('#qr').src=q.image;$('#qrStatus').textContent='请使用哔哩哔哩客户端扫码';qrTimer=setInterval(async()=>{try{let s=await req('/api/qr/poll?key='+encodeURIComponent(q.key));$('#qrStatus').textContent=s.message||'等待扫码';if(s.code===0){clearInterval(qrTimer);$('#qrStatus').textContent='登录成功';await sessionStatus();await loadFolders();setTimeout(()=>$('#loginDialog').close(),600)}else if(s.code===86038){clearInterval(qrTimer);$('#qrStatus').textContent='二维码已失效，请刷新'}}catch(e){$('#qrStatus').textContent=e.message}},1800)}catch(e){$('#qrStatus').textContent=e.message}}
$('#login').onclick=()=>{$('#loginDialog').showModal();startQR()};$('#newQR').onclick=startQR;$('#closeLogin').onclick=()=>{clearInterval(qrTimer);$('#loginDialog').close()};$('#loginSubmit').onclick=async()=>{try{let u=await post('/api/session',{cookie:$('#cookie').value});$('#account').textContent=u.uname;clearInterval(qrTimer);$('#loginDialog').close();$('#cookie').value='';await loadFolders()}catch(e){$('#loginMsg').textContent=e.message}};
$('#cancelDownload').onclick=()=>$('#downloadDialog').close();$('#confirmDownload').onclick=async()=>{let p=chosen.info.pages[+$('#page').value],after=chosen.sourceFolder?$('#after').value:'';try{await post('/api/download',{bvid:chosen.info.bvid,cid:p.cid,aid:chosen.aid,title:chosen.info.title,part:p.part,mode:$('#mode').value,qn:+$('#qn').value,output:$('#output').value,duration:p.duration,pageNumber:p.page,pageCount:chosen.info.pages.length,after,sourceFolder:chosen.sourceFolder,targetFolder:+$('#target').value});$('#downloadDialog').close();refreshTasks()}catch(e){alert(e.message)}};
$('#shutdown').onclick=async()=>{if(confirm('退出 BiliGreen？正在下载的任务会中断。')){await post('/api/shutdown',{});document.body.innerHTML='<main><section class="panel"><h2>BiliGreen 已退出</h2><p class="hint">现在可以关闭此页面。</p></section></main>'}};
function size(n){if(!n)return'0 B';let u=['B','KB','MB','GB'],i=Math.min(3,Math.floor(Math.log(n)/Math.log(1024)));return(n/1024**i).toFixed(i?1:0)+' '+u[i]}async function refreshTasks(){let ts=await req('/api/tasks');$('#tasks').innerHTML=ts.length?ts.map(t=>'<div class="task"><div>'+esc(t.name)+'</div><div class="meta">'+(t.part_info?esc(t.part_info)+' · ':'')+(t.duration?'长度 '+formatTime(t.duration)+' · ':'')+esc(t.status)+' · '+size(t.downloaded)+' / '+size(t.total)+'</div><progress max="'+(t.total||1)+'" value="'+t.downloaded+'"></progress>'+(t.playable?'<button class="playTask" data-id="'+esc(t.id)+'" data-name="'+esc(t.name)+'" data-duration="'+t.duration+'" data-part="'+esc(t.part_info||'单P')+'">在线播放</button>':'')+(t.error?'<div class="error">'+esc(t.error)+'</div>':'')+(t.post_action?'<div class="success">'+esc(t.post_action)+'</div>':'')+'</div>').join(''):'暂无任务'}
document.addEventListener('click',e=>{let b=e.target.closest('.playTask');if(!b)return;$('#playerTitle').textContent=b.dataset.name;$('#playerMeta').textContent=b.dataset.part+' · 长度 '+formatTime(+b.dataset.duration);$('#playerError').textContent='';$('#player').src='/api/media?id='+encodeURIComponent(b.dataset.id);$('#playerDialog').showModal();$('#player').play().catch(()=>{})});$('#player').onerror=()=>{$('#playerError').textContent='浏览器不支持此视频编码，但文件已完整下载。上方仍可查看长度和分P信息。'};$('#closePlayer').onclick=()=>{$('#player').pause();$('#player').removeAttribute('src');$('#player').load();$('#playerDialog').close()};
async function initSettings(){let s=await req('/api/settings'),saved=localStorage.getItem('biligreen.output')||s.defaultDownloadDir;$('#output').value=saved;$('#pathDisplay').textContent=saved;$('#dialogPath').textContent=saved}$('#savePath').onclick=()=>{let p=$('#output').value.trim();if(!p)return;localStorage.setItem('biligreen.output',p);$('#pathDisplay').textContent=p;$('#dialogPath').textContent=p};$('#openFolder').onclick=async()=>{try{let v=await post('/api/open-folder',{path:$('#output').value});$('#pathDisplay').textContent=v.path;$('#output').value=v.path;localStorage.setItem('biligreen.output',v.path)}catch(e){alert(e.message)}};
setInterval(refreshTasks,1000);initSettings();feed();sessionStatus();refreshTasks();
</script></body></html>`
